name: Build & Publish to GH pages
on:
  push:
    tags:
      - 'publish*'
jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
      - name: Install LaTeX dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y     \
            texlive-latex-recommended \
            texlive-latex-extra       \
            texlive-fonts-recommended \
            texlive-fonts-extra       \
            texlive-xetex             \
            latexmk                   \
            xindy
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.0
      - name: Install IJulia and Setup Project
        shell: bash -l {0}
        run: |
          julia -e 'using Pkg; Pkg.add("IJulia");'
          julia --project --threads auto -e 'using Pkg; Pkg.instantiate();'
      # Download Jupyter Book Cache
      - name: Download "build" folder (cache)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cache.yml
          branch: main
          name: build-cache
          path: _build
      # Build Assets for Julia site
      - name: Build Download Notebooks (sphinx-tojupyter)
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./ --builder=custom --custom-builder=jupyter
          zip -r download-notebooks.zip _build/jupyter
      - uses: actions/upload-artifact@v2
        with:
          name: download-notebooks
          path: download-notebooks.zip
      - name: Copy Download Notebooks for GH-PAGES
        shell: bash -l {0}
        run: |
          mkdir -p _build/html/_notebooks
          rsync -r  _build/jupyter/ _build/html/_notebooks/s
      # Build Website
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./ -W --keep-going
      - name: Deploy website to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
      - name: Upload "_build" folder (cache)
        uses: actions/upload-artifact@v2
        with:
          name: build-publish
          path: _build
